### ISSUE TITLE
Approximate Pareto front for RE21 is incorrect?

### ISSUE THREAD

**Issue by bolongcheng** [ryojitanabe/reproblems#1]
The values in `reference_points_RE21.dat` don't match what was shown in the Figure 2a in the paper.

**Comment by ryojitanabe** [comment]
Thanks, but I do not think so. It seems that the two-dimensional points in "reference_points_RE21.dat" and Fig. 2a are the same.

**Comment by bolongcheng** [comment]
Ok, my mistake here. I have trouble getting any results that's close to the Pareto front that you have for this particular problem (while having no trouble at all with the other problems).  For example:
RE21:
![paretos](https://user-images.githubusercontent.com/22994554/89968006-aa674d80-dc07-11ea-9bff-35a7e4a54a0e.png) 
RE22:
![paretos_22](https://user-images.githubusercontent.com/22994554/89968485-bf90ac00-dc08-11ea-9b6e-3c1aa8ee6b58.png)

I am implementing the functions in python using the supplement material. I think there is perhaps a typo in the matlab code. Should `E = 2e5` instead of [`E = 2 * 10e5`](https://github.com/ryojitanabe/reproblems/blob/0ddd380bcca4a0ef490fee1b494a46ab533c334c/reproblem_matlab_ver/RE21.m#L29) which is not `2 x 10^5` as you have written in the supplement. Maybe this is the cause?

Thanks.

**Comment by ryojitanabe** [comment]
Thank you for the explanation. You are right. "E = 2 * 10e5" (=2 * 10^6) should be "E = 2e5" (=2 * 10^5).

**Comment by ryojitanabe** [comment]
"G = 11.5 * 10e+6" (=11.5 * 10^7) in RE25 should also be "G = 11.5 * 1e+6" (=11.5 * 10^6).
