### ISSUE TITLE
RE problems in jMetal 5.10

### ISSUE THREAD

**Issue by ajnebro** [ryojitanabe/reproblems#2]
Hi @ryojitanabe 
  Thanks for providing the source code of the RE problems in jMetal 4.5. 

  I have just adapted them to the last stable version (jMetal 5.10) in GitHub (https://github.com/jMetal/jMetal). The repository also includes the reference fronts in CSV format (https://github.com/jMetal/jMetal/tree/master/resources/referenceFrontsCSV).

Regards,

Antonio

**Comment by ajnebro** [comment]
Related to Issue #1, the four-bar truss problem (i.e., RE21) was already included in jMetal and the front returned by some optimizers is far from the provided Pareto front approximation for that problem:


![imagen](https://user-images.githubusercontent.com/1889196/94803909-46ccf580-03ea-11eb-92f6-a41f700e4109.png)

**Comment by ryojitanabe** [comment]
Thank you for adapting the RE problem set to jMetal 5.10 (and sorry for that I still use the legacy jMetal 4.5). As you know, the reference files of RE21 and RE25 are incorrect. I will perform a re-experiment and update them. I appreciate your patience as it may take some time.
