### ISSUE TITLE
matlab implementation of RE21 lower bound is incorrect

### ISSUE THREAD

**Issue by linjunhe** [ryojitanabe/reproblems#4]
According to the RE21 formulation in the supp file, 
the lower bound of RE21 for x2 and x3 should be **sqrt(2)\*a** instead of **sqrt(a)**.

That is, in the _main.m_ file, 
lowerBounds = [tmpVar sqrt(tmpVar) sqrt(tmpVar) tmpVar];
should be replace by 
lowerBounds = [tmpVar sqrt(2)*tmpVar sqrt(2)*tmpVar tmpVar];

After this modification, the obtained results are consistent with the _reference_points_RE21.dat_ file.

**Comment by ryojitanabe** [comment]
Thanks for pointing out the bug. I have fixed it.
