### ISSUE TITLE
Error typo Problem Problem Re3-7-5 constraint g11 supplementary material pdf

### ISSUE THREAD

**Issue by salomonl** [ryojitanabe/reproblems#7]
Hey @ryojitanabe. Thank you a lot for having made this collection of real analytical problems available.

There is an typo error for problem Re3-7-5. In constraint g11, the bar of sqrt should englobe the `1.575 * 1e8` value. You fixed it for example in the `c` implementation but the supplementary material pdf was not updated.

**Comment by ryojitanabe** [comment]
Thank you for pointing out the typo in equation S.73 in the supplementary material. I have fixed it.
