### ISSUE TITLE
Difference between implementation and description of problem RE4-6-2

### ISSUE THREAD

**Issue by salomonl** [ryojitanabe/reproblems#8]
Hey @ryojitanabe. Thank you for having coded the examples in different languages, it helped me a lot to debug my code which uses these examples.

There is a difference between the description of constraint `g7 = 500000 - DWT` in the supplementary material pdf and the way it is implemented for example in the `c` version or the `python` version. In this case, the constraint is `g7 = 50000.0 -DWT`. I took a look in the original implementation described in the original paper

> Parsons, M. G., & Scott, R. L. (2004). Formulation of Multicriterion Design optimization Problems For Solution With Scalar Numerical Optimization Methods. _Journal of Ship Research_, 48(1), 61-76.

which corresponds to `g7 = 500000 - DWT`. Is there a reason for which you removed a 0 ?

Maybe another error of typo in the same problem. When I look at the equation `S-100`, I understand it as the fact that the `annual_cargo` variable is negative as `annual_cargo = - CARGO_DWT * RTPA`. Consequently, one user, when looking at the problem can think (it was my case) that `f1 = annual_cost / annual_cargo` is negative, which is not the case, as it is clarified by your implementation. The simplest will be to make the following correction: `f3 = - annual_cargo = - CARGO_DWT * RTPA` or `-f3 = annual_cargo = cargo_dwt * RTPA`.

Thank you again for having collected in the litterature this great set of real benchmarks !

**Comment by ryojitanabe** [comment]
Thank you for pointing out the bug and the typo. I have fixed them.
